name: CI Pipeline
on:
  pull_request:
    branches:
      - prod
    types:
      - closed

jobs:
  build:
    runs-on: debian-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: '2203'
          source_dir: ./dist
          target: /var/www/ldesfontaine.me/my-portfolio
